### ISSUE TITLE
Making it independent from UT

### ISSUE THREAD

**Issue by vincentmorneau** [rafael-trevisan/apex-plugin-peekaboo#1]
Very impressive plugin. 

As I was browsing through the code, I notice some hardcoded references to Universal Theme classes. Example `t-Form-fieldContainer` here https://github.com/rafael-trevisan/apex-plugin-peekaboo/blob/master/server/js/plugin.js#L73 

It means that the plugin is tied to UT.

For instance, it would not work on another custom theme, like this one: https://github.com/vincentmorneau/material-apex/blob/master/templates/Fields/Standard.hbs#L2 where the container class is `ma-field-container`

I don't know exactly how we could make it generic, but it's something to keep in mind.

Great job again. Looking forward to see more open source from you!

**Comment by rafael-trevisan** [comment]
Thanks, @vincentmorneau! I'm glad to hear you liked it 😎 

Excellent point!

I think it might work if the plugin looked for "#CURRENT_ITEM_NAME#_CONTAINER" instead, for i.e.

```
$(affectedElement).parents(`#${id}_CONTAINER`).attr('data-bind', `visible: peekaboo('${id}')`);
```

I mean, it might work with UT, material-apex and any other custom theme as long it uses `_CONTAINER` as postfix for the field container element.

I'll give a try.

Thanks again 👍

**Comment by vincentmorneau** [comment]
I think that's a reasonable approach, as long as it's case insensitive (`container` vs `Container`)

**Comment by rafael-trevisan** [comment]
Hey @vincentmorneau!

Your suggestion has been implemented [here](https://github.com/rafael-trevisan/apex-plugin-peekaboo/releases/tag/v18.2.0) 😎 

By the way, what a nice surprise those desktop notifications (TERMINAL-NOTIFIER)! Such a great work! 👍
